apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: l2cruns.tmax.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    description: Current status of L2cRun
    name: Status
    type: string
  - JSONPath: .status.phase
    description: Currently running phase of L2cRun
    name: Phase
    type: string
  - JSONPath: .status.startTime
    description: Time started the L2cRun
    name: StartTime
    type: date
  - JSONPath: .status.completionTime
    description: Time completed the L2cRun
    name: CompletionTime
    type: date
  group: tmax.io
  names:
    kind: L2CRun
    listKind: L2CRunList
    plural: l2cruns
    singular: l2crun
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: L2CRun is the Schema for the l2cruns API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: L2CRunSpec defines the desired state of L2CRun
          properties:
            l2cName:
              description: L2cName is the object name of L2c to be referred
              type: string
          required:
          - l2cName
          type: object
        status:
          description: L2CRunStatus defines the observed state of L2CRun
          properties:
            completionTime:
              format: date-time
              type: string
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            message:
              type: string
            phase:
              type: string
            startTime:
              format: date-time
              type: string
            status:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
