apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: l2cs.tmax.io
spec:
  group: tmax.io
  names:
    kind: L2C
    listKind: L2CList
    plural: l2cs
    singular: l2c
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: L2C is the Schema for the l2cs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: L2CSpec defines the desired state of L2C
          properties:
            accessCode:
              type: string
            dbMigrate:
              type: boolean
            dbSourceIp:
              pattern: '[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*'
              type: string
            dbSourcePassword:
              type: string
            dbSourcePort:
              format: int32
              type: integer
            dbSourceSid:
              type: string
            dbSourceType:
              enum:
              - ORACLE
              type: string
            dbSourceUser:
              type: string
            dbTargetPassword:
              type: string
            dbTargetServiceType:
              enum:
              - ClusterIP
              - LoadBalancer
              - NodePort
              type: string
            dbTargetStorageSize:
              type: string
            dbTargetType:
              enum:
              - TIBERO
              type: string
            dbTargetUser:
              type: string
            gitRevision:
              type: string
            gitUrl:
              type: string
            imageRegistrySecretName:
              type: string
            imageUrl:
              type: string
            projectName:
              type: string
            wasPackageServerUrl:
              type: string
            wasPort:
              format: int32
              type: integer
            wasServiceType:
              enum:
              - ClusterIP
              - LoadBalancer
              - NodePort
              type: string
            wasSourceType:
              enum:
              - wildfly
              type: string
            wasTargetType:
              enum:
              - jeus
              type: string
          required:
          - accessCode
          - gitRevision
          - gitUrl
          - imageUrl
          - projectName
          - wasPort
          - wasSourceType
          - wasTargetType
          type: object
        status:
          description: L2CStatus defines the observed state of L2C
          properties:
            message:
              type: string
            status:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
