apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: l2c-role
rules:
  - apiGroups:
      - tmax.io
    resources:
      - templates
      - templateinstances
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - secrets
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - get
      - watch
      - list
